#!/bin/sh
REST_BASE="http://carrot.ooblick.com/newsbite/w1"

echo "=== Adding a group"
curl -sSv -X PUT \
	-o output.json \
	-H 'Content-Type: application/json' \
	-d '{"name":"Test group","parent_id":-1}' \
	${REST_BASE}/group
echo "Output:"
cat output.json
echo ""

# Get the group ID, so we can delete it
# output.json should be of the form
#	{"id":"-42","parent":"-1","name":"Test group","state":"ok"}
GROUP_ID=`sed 's/.*"id":"\(-\?[0-9][0-9]*\).*/\1/' < output.json`

echo "=== Get information about this group"
curl -sSv -X GET \
	-o output.json \
	${REST_BASE}/group/${GROUP_ID}
echo "Output:"
cat output.json
echo ""

echo "=== List all groups"
curl -sSv -X GET \
	-o output.json \
	${REST_BASE}/group
echo "Output:"
cat output.json
echo ""

curl -sSv -X DELETE \
	-o output.json \
	-H 'Content-Type: application/json' \
	-d '{"name":"Test group","parent_id":-1}' \
	${REST_BASE}/group/${GROUP_ID}
echo "Output:"
cat output.json
echo ""
